### ISSUE TITLE
feat: delete an entity in the gui

### ISSUE THREAD

**Issue by iMeaNz** [NexoEngine/game-engine#19]

**Comment by ThomasParenteau** [comment]
![Image](https://github.com/user-attachments/assets/5e23c7e2-2fd1-48ad-9437-d7147cc11f5f)

@iMeaNz 
Je vois déjà un bouton delete relié aux entities dans la liste, est ce que l'issue parle d'un autre bouton ou d'un improve de ce dernier ?

**Comment by iMeaNz** [comment]
Oh, je savais pas que ca avait été déjà implémenté ici.
J'parlais aussi de pouvoir delete une entité via suppr si elle est selectionnée par exemple ou en faisant clic droit.
Tu peux check la branche `feat/editor-improvement` pour voir ce que j'ai déjà fait niveau raccourci, et surtout sur celle la c'est possible de switch en cliquant sur l'entité dans la scène plutot que dans le scene tree donc surement plus simple pour cette feature

**Comment by ThomasParenteau** [comment]
Ok ça marche merci du retour rapide ! Je checkerai ça !
