### ISSUE TITLE
bug: glfw/opengl warning with new versions

### ISSUE THREAD

**Issue by iMeaNz** [NexoEngine/game-engine#43]
# Description
On linux, the newly bumped imgui versions seems to trigger an opengl/gflw warning
`
[ERROR]: 65539, Invalid window attribute 0x0002000D
`
There are some info on this issue : 
https://github.com/ocornut/imgui/issues/3451

# Temporary fix
For now i just commented out the open/glfw warning logs:
```cpp
case GLFW_INVALID_ENUM:
case GLFW_INVALID_VALUE:
    //LOG(NEXO_WARN, "[OPENGL WARNING] ({}): {}", error, description);
break;
```

**Comment by Thyodas** [comment]
Fixed in #45 
Removed comment, fixed in #49
